version: '3.8'

services:
  web:
    build: #./web # assuming Dockerfile for Flask is in a 'web' directory
      context: ..
      dockerfile: ./docker/flask_dockerfile
    container_name: flask_container
    environment:
      # - DATABASE_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
      - DATABASE_URL=${DATABASE_URL}
      # db is the name of the service in docker-compose.yml
      - FLASK_ENV=development
    ports:
      - "5001:5000"
    depends_on:
      - db
    networks:
      - flask_postgres_network
    volumes:
        - ../models:/app/models 
        - ../uploads:/app/uploads 
        - ../static:/app/static
        - ../templates:/app/templates 
        - ../routes:/app/routes

  db:
    image: postgres
    container_name: postgres_container
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - flask_postgres_network

volumes:
  postgres_data:

networks:
  flask_postgres_network:
    driver: bridge


# docker-compose up -d # -d for detached mode or
# docker-compose up --build

# docker-compose down

# docker compose -p postgres_container -f ./docker/docker-compose.yml up --build -d

# --env-file .env # to use env file from root directory

