"""empty message

Revision ID: 644a70a4e190
Revises: 
Create Date: 2023-09-23 22:17:33.316167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '644a70a4e190'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_model',
    sa.Column('model_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('path', sa.String(length=120), nullable=False),
    sa.Column('uploaded_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('model_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('ml_model')
    # ### end Alembic commands ###
